node.id=1
listeners=PLAINTEXT://127.0.0.1:37789
advertised.listeners=PLAINTEXT://127.0.0.1:37789
cluster.id=kafkalite-single-broker
log.dirs=/home/youngseok/workspace/kafkalite/.worktree/publish-prep/.benchmarks/20260413T012819Z-6db643f/scenario-bench-produce-multi_partition/data
num.partitions=3
